# .goreleaser.yml
# Build customization
builds:
  - binary: terraform-provider-cosmic
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  name_template: "{{ .Binary }}-{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  format: binary
checksum:
  name_template: "{{ .ProjectName }}_{{ .Tag }}_checksums.txt"
release:
  draft: true
  prerelease: false
  name_template: "{{ .Tag }}"
changelog:
  filters:
    exclude:
      - '(?!Merge pull request)'
